version: '3.8'
services:
  db:
    image: postgres:15.1
    restart: always
    env_file:
      - database.env
    ports:
      - '5432:5432'
  core:
    image: post-cat-core:0.0.5
    network_mode: host
    env_file:
      - database.env
    ports:
      - '8888:8888'
  telegram:
    network_mode: host
    image: post-cat-telegram:0.0.5
    env_file:
      - telegram.env
    ports:
      - '8090:8090'
  rest:
    network_mode: host
    image: post-cat-public-api:0.0.5
    env_file:
      - database.env
    ports:
      - '9090:9090'
volumes:
  db:
    driver: local